"""
OpenEnv-Compliant FastAPI Server for KubeCost-Gym

Uses openenv-core's HTTPEnvServer and create_fastapi_app to expose
the KubeCostEnv environment as a REST API.

This server provides the standard OpenEnv REST endpoints:
- POST /reset   - Reset environment to initial state
- POST /step    - Execute action and get next observation
- GET /state    - Get current environment state
- GET /health   - Health check

Entry point: server/app.py:app (for uvicorn)
Or: server/app.py:main() (standalone startup)
Runs on: port 7860 (HF Spaces default)
"""

import logging
import os
import sys
from pathlib import Path
from typing import Callable

import uvicorn
from openenv.core import create_fastapi_app

# Add parent directory to path so we can import modules from root
sys.path.insert(0, str(Path(__file__).parent.parent))

from env import KubeCostEnv
from inference import validate_env, EnvironmentValidationError
from models import Action, Observation

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


# ===== OpenEnv Environment Factory =====

def create_env() -> KubeCostEnv:
    """
    Factory function for creating KubeCostEnv instances.
    
    The openenv-core create_fastapi_app expects a callable that returns
    an Environment instance. This allows the server to create fresh
    environment instances for each session/reset request.
    
    Returns:
        KubeCostEnv: A new environment instance
    """
    # Use default trace path for initial environment
    # Clients can override via reset(trace_path=...) on /reset endpoint
    env = KubeCostEnv(trace_path="traces/trace_v1_coldstart.json")
    return env


# ===== FastAPI App Setup =====

# Create FastAPI app using openenv-core's automatic REST API generator
# This handles /reset, /step, /state, /health endpoints automatically
app = create_fastapi_app(
    env=create_env,
    action_cls=Action,
    observation_cls=Observation,
    max_concurrent_envs=None,  # No limit on concurrent sessions
)

# Store logger in app state for access across endpoints
app.state.logger = logger


@app.on_event("startup")
async def startup_event():
    """Validate environment variables on startup."""
    try:
        validate_env()
        logger.info("✓ Environment variables validated")
        logger.info("  - API_BASE_URL: set")
        logger.info("  - MODEL_NAME: set")
        logger.info("  - HF_TOKEN: set")
    except EnvironmentValidationError as e:
        logger.warning(f"⚠ Environment validation warning: {e}")
        logger.warning("  (Agent will not be available, but server will run)")
    except Exception as e:
        logger.warning(f"⚠ Startup warning: {e}")


@app.get("/")
async def root():
    """API information endpoint."""
    return {
        "name": "KubeCost-Gym OpenEnv API",
        "version": "3.0",
        "description": "Kubernetes cost optimization RL environment via OpenEnv standard",
        "framework": "openenv-core",
        "endpoints": {
            "POST /reset": {
                "description": "Reset environment to initial state",
                "params": {"trace_path": "optional trace file path"},
            },
            "POST /step": {
                "description": "Execute action",
                "body": {"action": "Action object"},
            },
            "GET /state": {
                "description": "Get current environment state",
            },
            "GET /health": {
                "description": "Health check",
            },
            "GET /docs": {
                "description": "Interactive API documentation (Swagger UI)",
            },
        },
        "docs_url": "/docs",
        "openapi_url": "/openapi.json",
    }


def main():
    """
    Main entry point for running the server standalone.
    
    Can be invoked as:
    - python server/app.py
    - uv run python server/app.py
    - uv run kubecost-gym (from pyproject.toml entry point)
    """
    logger.info("=" * 70)
    logger.info("KubeCost-Gym OpenEnv REST API Server")
    logger.info("=" * 70)

    # Get port and host from environment
    port = int(os.environ.get("PORT", 7860))
    host = os.environ.get("SERVER_NAME", "0.0.0.0")

    logger.info(f"\nStarting server on {host}:{port}")
    logger.info("\nOpenEnv REST Endpoints (auto-generated by openenv-core):")
    logger.info("  - POST /reset          - Reset environment")
    logger.info("  - POST /step           - Execute action")
    logger.info("  - GET  /state          - Get environment state")
    logger.info("  - GET  /health         - Health check")
    logger.info("  - GET  /docs           - Interactive API docs (Swagger UI)")
    logger.info("  - GET  /openapi.json   - OpenAPI schema")
    logger.info("  - GET  /                - API information")

    logger.info("\n" + "=" * 70)

    # Run using uvicorn
    uvicorn.run(
        app,
        host=host,
        port=port,
        log_level="info",
    )


if __name__ == "__main__":
    main()
